# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tacojs.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
   - jemoji
   - jekyll-redirect-from
future: true
timezone: Etc/UTC

# Collections
collections:
  posts:
    title: Posts
    output: true
  meetups:
    title: Meetups
    output: true
    permalink: "/meetup/:path"
    layout: meetup
    location: TBD
    address: 1234 Market Street
    intersection: 12th & Market
  media:
    title: Media
    output: true

# Metadata
keywords: "tacojs, taco, javascript, meetup, philadelphia, node.js, talks, developer, meetup.com, libertyjs"
google-fonts: "BioRhyme:700|Suez+One|Work+Sans:400,700"
google-fonts-subsets: "latin"
google-analytics: "UA-XXXXXXXX-1"

# Commonly used lingo
title: TacoJS
location: Philadelphia, PA, USA
email: hello@victorlourng.com
description: A fun night of code & tacos.
handle: TacoJS
twitter: tacojs_phl
github: tacojs
slack: "http://phillydev.org/"
